### ISSUE TITLE
nilearn import error

### ISSUE THREAD

**Issue by araikes** [neurostuff/NiMARE#964]
## Summary

I updated to `0.7.0` today in an Apptainer dedicated to nimare. I went to run the script that I know works on `0.6.1` and got the following error:

```
  File "/opt/conda/lib/python3.13/site-packages/nimare/meta/ibma.py", line 19, in <module>
    from nilearn._utils.niimg_conversions import check_same_fov
ImportError: cannot import name 'check_same_fov' from 'nilearn._utils.niimg_conversions' (/opt/conda/lib/python3.13/site-packages/nilearn/_utils/niimg_conversions.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    from nimare.meta import ibma
  File "/opt/conda/lib/python3.13/site-packages/nimare/__init__.py", line 12, in <module>
    from . import (
    ...<12 lines>...
    )
  File "/opt/conda/lib/python3.13/site-packages/nimare/decode/__init__.py", line 3, in <module>
    from . import continuous, discrete, encode
  File "/opt/conda/lib/python3.13/site-packages/nimare/decode/continuous.py", line 18, in <module>
    from nimare.meta.cbma.base import CBMAEstimator
  File "/opt/conda/lib/python3.13/site-packages/nimare/meta/__init__.py", line 3, in <module>
    from . import ibma, kernel
  File "/opt/conda/lib/python3.13/site-packages/nimare/meta/ibma.py", line 22, in <module>
    from nilearn._utils.niimg_conversions import _check_same_fov as check_same_fov
ImportError: cannot import name '_check_same_fov' from 'nilearn._utils.niimg_conversions' (/opt/conda/lib/python3.13/site-packages/nilearn/_utils/niimg_conversions.py)
```

I double checked and I have `nilearn=0.13.0` installed the following import alone works:
```
from nilearn.image.image import check_same_fov
```

Some how the new try/except logic isn't finding the right version.

**Comment by araikes** [comment]
Ack... nevermind... Apparently i forgot to remove the `==0.6.1` from my apptainer definition...
